context:
  version: "2.8.4"

package:
  name: css-variables-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/css-variables-language-server/-/css-variables-language-server-${{ version }}.tgz
  sha256: 89885e64a59af8f96c51af70db2a340ade59e4d9df5e861af99af5cea78905a9

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "css-variables-language-server 2>&1 | grep -q 'Connection input stream is not set.'"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language server for CSS variables
  homepage: https://github.com/vunguyentuan/vscode-css-variables
  repository: https://github.com/vunguyentuan/vscode-css-variables

extra:
  recipe-maintainers:
    - danielnachun
