context:
  version: "2.7.2"

package:
  name: css-variables-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/css-variables-language-server/-/css-variables-language-server-${{ version }}.tgz
  sha256: 2d79f7890f372b2d0e3301fb8f7b19daae73230639d186067ac32c82f619608f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "css-variables-language-server 2>&1 | grep -q 'Connection input stream is not set.'"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language server for CSS variables
  homepage: https://github.com/vunguyentuan/vscode-css-variables
  repository: https://github.com/vunguyentuan/vscode-css-variables

extra:
  recipe-maintainers:
    - danielnachun
